global:
  external_labels:
      monitor: 'eastpaloalto'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.1.1:9093']

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'home'
    static_configs:
      - targets: ['192.168.1.1:8000']
  - job_name: mqtt-exporter
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.1.1:9000']
  - job_name: switches
    static_configs:
      - targets: ['192.168.1.1:7002']
