global:
  external_labels:
      monitor: 'eastpaloalto'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.1.1:9093']

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server'
    static_configs:
      - targets: ['192.168.1.1:9558']

  - job_name: 'raspi'
    static_configs:
      - targets: ['192.168.1.96:9558']

  - job_name: 'home'
    static_configs:
      - targets: ['192.168.1.1:8000']

  - job_name: mqtt-exporter
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.1.1:9000']

    metric_relabel_configs:
    
    - source_labels: [ topic ]
      regex: 'zigbee2mqtt_[a-z]+_0x[0-9a-f]+'
      action: drop
    
    - source_labels: [ topic ]
      regex: 'homeassistant_.+'
      action: drop

    - source_labels: [ topic ]
      regex: 'zigbee2mqtt_[a-z]+_device_(.*)_[a-z]+(_get|_set)?'
      replacement: '$1'
      action: replace
      target_label: "location"

    - source_labels: [ topic ]
      regex: 'zigbee2mqtt_[a-z]+_device_.*_([a-z]+)(_get|_set)?'
      replacement: '$1'
      action: replace
      target_label: "sensor_type"

    - source_labels: [ topic ]
      regex: 'zigbee2mqtt_([a-z]+)_device_.*'
      replacement: '$1'
      action: replace
      target_label: "network"

    - source_labels: [ topic ]
      regex: 'esphome_(.*)'
      replacement: '$1'
      action: replace
      target_label: "location"

    - source_labels: [ topic ]
      regex: 'esphome_.*'
      replacement: 'esphome'
      action: replace
      target_label: "network"

    - source_labels: [ topic ]
      regex: 'esphome_.*'
      replacement: 'hvac'
      action: replace
      target_label: "sensor_type"

  - job_name: switches
    static_configs:
      - targets: ['192.168.1.1:7002']

  - job_name: netscan
    static_configs:
      - targets: ['192.168.1.1:7004']
