global:
  external_labels:
      monitor: 'eastpaloalto'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['${IP}:9093']

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: zigbee
    metrics_path: '/'
    static_configs:
      - targets: ['${IP}:9000']