esphome:
  name: hvac-kitchen
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "hvackitchen"
    password: "fallbackPASSWORD"

captive_portal:

ota:

logger:
  baud_rate: 0

mqtt:
  broker: 192.168.1.1

remote_transmitter:
  pin: GPIO5
  carrier_duty_percent: 100%

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

climate:
  platform: midea
  name: kitchen
  autoconf: true
  beeper: false
  supported_swing_modes:
    - VERTICAL
    - HORIZONTAL
    - BOTH
  supported_modes:
    - FAN_ONLY
    - COOL
    - HEAT
  action_state_topic: esphome/kitchen/action_state
  away_state_topic: esphome/kitchen/away_state
  away_command_topic: esphome/kitchen/away_command
  current_temperature_state_topic: esphome/kitchen/current_temperature_state
  fan_mode_state_topic: esphome/kitchen/fan_mode_state
  fan_mode_command_topic: esphome/kitchen/fan_mode_command
  mode_state_topic: esphome/kitchen/mode_state
  mode_command_topic: esphome/kitchen/mode_command
  swing_mode_state_topic: esphome/kitchen/swing_mode_state
  swing_mode_command_topic: esphome/kitchen/swing_mode_command
  target_temperature_state_topic: esphome/kitchen/target_temperature_state
  target_temperature_command_topic: esphome/kitchen/target_temperature_command
  target_temperature_high_state_topic: esphome/kitchen/target_temperature_high_state
  target_temperature_high_command_topic: esphome/kitchen/target_temperature_high_command
  target_temperature_low_state_topic: esphome/kitchen/target_temperature_low_state
  target_temperature_low_command_topic: esphome/kitchen/target_temperature_low_command