esphome:
  name: hvac-office
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "hvacoffice"
    password: "fallbackPASSWORD"

captive_portal:

ota:

logger:
  baud_rate: 0

mqtt:
  broker: 192.168.1.1

remote_transmitter:
  pin: GPIO5
  carrier_duty_percent: 100% 

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

climate:
  platform: midea
  name: office
  autoconf: true
  beeper: false
  supported_modes:
    - FAN_ONLY
    - COOL
    - HEAT
  action_state_topic: esphome/office/action_state
  away_state_topic: esphome/office/away_state
  away_command_topic: esphome/office/away_command
  current_temperature_state_topic: esphome/office/current_temperature_state
  fan_mode_state_topic: esphome/office/fan_mode_state
  fan_mode_command_topic: esphome/office/fan_mode_command
  mode_state_topic: esphome/office/mode_state
  mode_command_topic: esphome/office/mode_command
  swing_mode_state_topic: esphome/office/swing_mode_state
  swing_mode_command_topic: esphome/office/swing_mode_command
  target_temperature_state_topic: esphome/office/target_temperature_state
  target_temperature_command_topic: esphome/office/target_temperature_command
  target_temperature_high_state_topic: esphome/office/target_temperature_high_state
  target_temperature_high_command_topic: esphome/office/target_temperature_high_command
  target_temperature_low_state_topic: esphome/office/target_temperature_low_state
  target_temperature_low_command_topic: esphome/office/target_temperature_low_command