esphome:
  name: night_light
  # platform: ESP8266
  # board: esp12e
  on_boot:
    priority: -100
    then:
      - light.turn_off: status


esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "esp-test-1"
    password: "fallbackPASSWORD"

captive_portal:

ota:
api:

light:
  - platform: binary
    name: red
    id: red
    output: pin_D5
    on_turn_on:
      then:
        - light.turn_off:
            id: green
  - platform: binary
    name: green
    id: green
    output: pin_D7
    on_turn_on:
      then:
        - light.turn_off:
            id: red
        # Turn off any scripts
  - platform: binary
    name: status
    id: status
    output: pin_D4

output:
  - id: pin_D3
    platform: gpio
    pin: GPIO0
  - id: pin_D4
    platform: gpio
    pin: GPIO2
    inverted: true
  - id: pin_D5
    platform: gpio
    pin: GPIO14
  - id: pin_D7
    platform: gpio
    pin: GPIO13
