esphome:
  name: night-light

esp8266:
  board: nodemcuv2
  restore_from_flash: True

wifi:
  ssid: !secret cactus_ssid
  password: !secret wifi_password
  ap:
    ssid: "night-light"
    password: "fallbackPASSWORD"
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.0.111
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4

ota:
  platform: esphome
api:
web_server:

logger:
  level: INFO

light:
  - platform: binary
    name: red
    id: red
    restore_mode: RESTORE_DEFAULT_OFF
    output: pin_D5
    on_turn_on:
      then:
        - light.turn_off:
            id: green
  - platform: binary
    name: green
    id: green
    restore_mode: RESTORE_DEFAULT_OFF
    output: pin_D7
    on_turn_on:
      then:
        - light.turn_off:
            id: red
  - platform: binary
    name: status
    id: status
    output: pin_D4

output:
  - id: pin_D3
    platform: gpio
    pin: GPIO0
  - id: pin_D4
    platform: gpio
    pin: GPIO2
    inverted: true
  - id: pin_D5
    platform: gpio
    pin: GPIO14
  - id: pin_D7
    platform: gpio
    pin: GPIO13

number:
  - name: reveil_hour
    id: reveil_hour
    platform: template
    optimistic: true
    min_value: 0
    max_value: 23
    step: 1
    restore_value: true
    mode: box
  - name: reveil_minute
    id: reveil_minute
    platform: template
    optimistic: true
    min_value: 0
    max_value: 59
    step: 1
    restore_value: true
    mode: box

time:
  - platform: homeassistant
    timezone: America/Los_Angeles
    id: pacific_time
    on_time:
      - seconds: /5
        then:
          - if:
              condition:
                lambda: >-
                  auto time = id(pacific_time).now();
                  auto reveil = int(id(reveil_hour).state) * 60 + int(id(reveil_minute).state);
                  auto now = time.hour * 60 + time.minute;
                  return now == reveil;
              then:
                - light.turn_on: green
