// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: air.proto

package air_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AirSvcClient is the client API for AirSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirSvcClient interface {
	ListRooms(ctx context.Context, in *ReqListRooms, opts ...grpc.CallOption) (*RspListRooms, error)
	ListHvacs(ctx context.Context, in *ReqListHvacs, opts ...grpc.CallOption) (*RspListHvacs, error)
	ListSensors(ctx context.Context, in *ReqListSensors, opts ...grpc.CallOption) (*RspListSensors, error)
	CheckRoom(ctx context.Context, in *ReqCheckRoom, opts ...grpc.CallOption) (*RspCheckRoom, error)
	CheckHvac(ctx context.Context, in *ReqCheckHvac, opts ...grpc.CallOption) (*RspCheckHvac, error)
	ConfigureRoom(ctx context.Context, in *ReqConfigureRoom, opts ...grpc.CallOption) (*RspConfigureRoom, error)
	ConfigureHvac(ctx context.Context, in *ReqConfigureHvac, opts ...grpc.CallOption) (*RspConfigureHvac, error)
}

type airSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewAirSvcClient(cc grpc.ClientConnInterface) AirSvcClient {
	return &airSvcClient{cc}
}

func (c *airSvcClient) ListRooms(ctx context.Context, in *ReqListRooms, opts ...grpc.CallOption) (*RspListRooms, error) {
	out := new(RspListRooms)
	err := c.cc.Invoke(ctx, "/air.service.AirSvc/ListRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airSvcClient) ListHvacs(ctx context.Context, in *ReqListHvacs, opts ...grpc.CallOption) (*RspListHvacs, error) {
	out := new(RspListHvacs)
	err := c.cc.Invoke(ctx, "/air.service.AirSvc/ListHvacs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airSvcClient) ListSensors(ctx context.Context, in *ReqListSensors, opts ...grpc.CallOption) (*RspListSensors, error) {
	out := new(RspListSensors)
	err := c.cc.Invoke(ctx, "/air.service.AirSvc/ListSensors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airSvcClient) CheckRoom(ctx context.Context, in *ReqCheckRoom, opts ...grpc.CallOption) (*RspCheckRoom, error) {
	out := new(RspCheckRoom)
	err := c.cc.Invoke(ctx, "/air.service.AirSvc/CheckRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airSvcClient) CheckHvac(ctx context.Context, in *ReqCheckHvac, opts ...grpc.CallOption) (*RspCheckHvac, error) {
	out := new(RspCheckHvac)
	err := c.cc.Invoke(ctx, "/air.service.AirSvc/CheckHvac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airSvcClient) ConfigureRoom(ctx context.Context, in *ReqConfigureRoom, opts ...grpc.CallOption) (*RspConfigureRoom, error) {
	out := new(RspConfigureRoom)
	err := c.cc.Invoke(ctx, "/air.service.AirSvc/ConfigureRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airSvcClient) ConfigureHvac(ctx context.Context, in *ReqConfigureHvac, opts ...grpc.CallOption) (*RspConfigureHvac, error) {
	out := new(RspConfigureHvac)
	err := c.cc.Invoke(ctx, "/air.service.AirSvc/ConfigureHvac", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirSvcServer is the server API for AirSvc service.
// All implementations must embed UnimplementedAirSvcServer
// for forward compatibility
type AirSvcServer interface {
	ListRooms(context.Context, *ReqListRooms) (*RspListRooms, error)
	ListHvacs(context.Context, *ReqListHvacs) (*RspListHvacs, error)
	ListSensors(context.Context, *ReqListSensors) (*RspListSensors, error)
	CheckRoom(context.Context, *ReqCheckRoom) (*RspCheckRoom, error)
	CheckHvac(context.Context, *ReqCheckHvac) (*RspCheckHvac, error)
	ConfigureRoom(context.Context, *ReqConfigureRoom) (*RspConfigureRoom, error)
	ConfigureHvac(context.Context, *ReqConfigureHvac) (*RspConfigureHvac, error)
	mustEmbedUnimplementedAirSvcServer()
}

// UnimplementedAirSvcServer must be embedded to have forward compatible implementations.
type UnimplementedAirSvcServer struct {
}

func (UnimplementedAirSvcServer) ListRooms(context.Context, *ReqListRooms) (*RspListRooms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRooms not implemented")
}
func (UnimplementedAirSvcServer) ListHvacs(context.Context, *ReqListHvacs) (*RspListHvacs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHvacs not implemented")
}
func (UnimplementedAirSvcServer) ListSensors(context.Context, *ReqListSensors) (*RspListSensors, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSensors not implemented")
}
func (UnimplementedAirSvcServer) CheckRoom(context.Context, *ReqCheckRoom) (*RspCheckRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRoom not implemented")
}
func (UnimplementedAirSvcServer) CheckHvac(context.Context, *ReqCheckHvac) (*RspCheckHvac, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHvac not implemented")
}
func (UnimplementedAirSvcServer) ConfigureRoom(context.Context, *ReqConfigureRoom) (*RspConfigureRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureRoom not implemented")
}
func (UnimplementedAirSvcServer) ConfigureHvac(context.Context, *ReqConfigureHvac) (*RspConfigureHvac, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureHvac not implemented")
}
func (UnimplementedAirSvcServer) mustEmbedUnimplementedAirSvcServer() {}

// UnsafeAirSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirSvcServer will
// result in compilation errors.
type UnsafeAirSvcServer interface {
	mustEmbedUnimplementedAirSvcServer()
}

func RegisterAirSvcServer(s grpc.ServiceRegistrar, srv AirSvcServer) {
	s.RegisterService(&AirSvc_ServiceDesc, srv)
}

func _AirSvc_ListRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqListRooms)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirSvcServer).ListRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/air.service.AirSvc/ListRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirSvcServer).ListRooms(ctx, req.(*ReqListRooms))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirSvc_ListHvacs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqListHvacs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirSvcServer).ListHvacs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/air.service.AirSvc/ListHvacs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirSvcServer).ListHvacs(ctx, req.(*ReqListHvacs))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirSvc_ListSensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqListSensors)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirSvcServer).ListSensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/air.service.AirSvc/ListSensors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirSvcServer).ListSensors(ctx, req.(*ReqListSensors))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirSvc_CheckRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCheckRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirSvcServer).CheckRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/air.service.AirSvc/CheckRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirSvcServer).CheckRoom(ctx, req.(*ReqCheckRoom))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirSvc_CheckHvac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCheckHvac)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirSvcServer).CheckHvac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/air.service.AirSvc/CheckHvac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirSvcServer).CheckHvac(ctx, req.(*ReqCheckHvac))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirSvc_ConfigureRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqConfigureRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirSvcServer).ConfigureRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/air.service.AirSvc/ConfigureRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirSvcServer).ConfigureRoom(ctx, req.(*ReqConfigureRoom))
	}
	return interceptor(ctx, in, info, handler)
}

func _AirSvc_ConfigureHvac_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqConfigureHvac)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirSvcServer).ConfigureHvac(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/air.service.AirSvc/ConfigureHvac",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirSvcServer).ConfigureHvac(ctx, req.(*ReqConfigureHvac))
	}
	return interceptor(ctx, in, info, handler)
}

// AirSvc_ServiceDesc is the grpc.ServiceDesc for AirSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "air.service.AirSvc",
	HandlerType: (*AirSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRooms",
			Handler:    _AirSvc_ListRooms_Handler,
		},
		{
			MethodName: "ListHvacs",
			Handler:    _AirSvc_ListHvacs_Handler,
		},
		{
			MethodName: "ListSensors",
			Handler:    _AirSvc_ListSensors_Handler,
		},
		{
			MethodName: "CheckRoom",
			Handler:    _AirSvc_CheckRoom_Handler,
		},
		{
			MethodName: "CheckHvac",
			Handler:    _AirSvc_CheckHvac_Handler,
		},
		{
			MethodName: "ConfigureRoom",
			Handler:    _AirSvc_ConfigureRoom_Handler,
		},
		{
			MethodName: "ConfigureHvac",
			Handler:    _AirSvc_ConfigureHvac_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "air.proto",
}
